version: "3"
services:
  client:
    build: ./client
    deploy:
      replicas: 1
      restart_policy:
        condition: always
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - jaxrs
#  hashgraph:
#    build: "./hashgraph workspace"
#    depends_on:
#      - couchdb
#    deploy:
#      replicas: 1
#      restart_policy: 
#        condition: always   
#    ports: 
#      - "51200-51299:51200-51299"
#      - "52200-52299:52200-52299"
  jaxrs:
    build: "./jaxrs workspace"
#    depends_on:
#      - hashgraph
    deploy:
      replicas: 1
      restart_policy:
        condition: always    
    ports:
     - "8888:8080"    
  couchdb:
    image: couchdb:2.1
    ports: 
      - "5984:5984"
    deploy:
      replicas: 1
      restart_policy:
        condition: always
