/**
 * Hashgraph Zoo API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: craig.drabik@txmq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface Zoo {
    lions?: Array<string>;
    tigers?: Array<string>;
    bears?: Array<string>;
}
