/**
 * Hashgraph Zoo API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: craig.drabik@txmq.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams }               from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';
import '../rxjs-operators';

import { Animal } from '../model/animal';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';
import { ExoDistributedEndpointService } from '../../app/exo/exo-distributed-endpoint.service';

/**
 * This class started life as a generated endpoint based on a Swagger definition.
 * Head over to http://swagger.io for more info on Swagger.
 * 
 * This service demonstrates how Angular applications can communicate with
 * a hashgraph network in two ways.  The first way is through a traditional
 * centralized REST API.  In this demo, it's buit on JAX-RS, also built from 
 * a skeleton generated from a Swagger definition.  That REST API communicates
 * with the Hashgraph through a secured socket connection and may suit 
 * applications that don't need to be fully distributed on the back end, or 
 * require the kinds of integrations typical of enterprise applications.
 * 
 * If you're building this type of application, you probably don't need Exo
 * on the client at all.  You can make requests to your API the same way you
 * always have, and the API isolates the client from the Hashgraph network.
 * 
 * The second method is to make requests against REST endpoints exposed by
 * the Hashgraph nodes themselves.  In this scheme, the application is protected
 * from having a middle tier that constitutes a single point of failure.  Exo
 * manages the communication between the application and the Hashgraph network.
 */
@Injectable()
export class DefaultService {

    /**
     * Base API path for accessing the centralized JAX-RS API.
     * In the Docker setup for this project, this URL is proxied
     * through NGINX running on the client container to the jaxrs 
     * container (no CORS issues).
     */
    private jaxBasePath = 'http://localhost:8080/HashgraphZoo/1.0.0';
    
    /**
     * Indicates whether or not we should query the Hashgraph directly.
     * This property is bound to the UI radio button and lets users switch
     * between communication methods.
     */
    public useHashgraph:boolean = true;

    /**
     * Hook for wiring in the distributed endpoint service to get
     * the path to make requests from.
     */
    protected get basePath():string {
        if (!this.useHashgraph) {
            return this.jaxBasePath; 
        } else {
            return this.distributedEndpoitnService.getBaseUrl();
        }
    }
    
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, 
                protected distributedEndpoitnService: ExoDistributedEndpointService,
                @Optional()@Inject(BASE_PATH) basePath: string, 
                @Optional() configuration: Configuration) {
        if (basePath) {
            //TODO:
            //this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            //TODO
            //this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }

    /**
     * adds an animal to the zoo
     * Adds an animal to the zoo
     * @param animal Animal to add
     */
    public addAnimal(animal?: Animal): Observable<{}> {

        return this.httpClient.post<any>(`${this.basePath}/zoo/animals`,
            animal,
            this.configureRequest()
        );
    }

    /**
     * Returns all the animals in the zoo
     * Returns all of the animals in the zoo 
     */
    public getZoo(): Observable<any> {
        return this.httpClient.get<any>(`${this.basePath}/zoo`, this.configureRequest());
    }

    public stopHashgraph():Observable<any> {
        return this.httpClient.get<any>(`${this.basePath}/shutdown`, this.configureRequest());
    }

    private configureRequest():Object {
        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];

        let httpContentTypeSelected:string = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return {
            headers: headers,
            withCredentials: this.configuration.withCredentials,
        };
    } 
}
